name: Bootcamp 2020 urdu

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: installinn Node
      use:  actions/setup-node@v2-beta
      with: 
        node-version: 12 
      name: installing surge 
      run: npm install -g surge 
    - name: deploying using surge 
      run: surge ./ bootcapm2020.surge.sh --token $ {{secret.SURGE_TOKEN}}
